
ALTER SESSION SET CONTAINER = FREEPDB1;
ALTER SESSION SET CURRENT_SCHEMA = spring_jdbc_oracle;

CREATE TABLE test_table (
  id     NUMBER(5)    NOT NULL PRIMARY KEY,
  val    VARCHAR2(50) NOT NULL,
  numval NUMBER(10)   NOT NULL
);
